dist: bionic
sudo: false

language: node_js
node_js:
  - "10"

cache:
  directories:
     - ./node_modules
     - /home/travis/.cache/Cypress

install:
  - npm install
  - npx cypress install

env:
  - COMMAND='lint'
  - COMMAND='policy'
  - COMMAND='unit'
  - COMMAND='e2e'
  - COMMAND='build'

script: "npm run ci-tests -- $COMMAND"
